services:
  bot:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot1:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      -  BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot2:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot3:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot4:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot5:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot6:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot7:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  bot8:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=<>
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  api:
    build:
      context: ./bot/
      dockerfile: Dockerfile-web
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
  
  dashboard:
    build: ./dashboard/
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
