services:
  bot:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot1:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=34c3a36e-0c27-4825-bc1a-9056d946d2cd
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot2:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=17c9e280-3877-483f-820d-21778437cb5e
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot3:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=247d2f92-6fd1-4ff4-8a00-1316a161d981
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot4:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=77e74f26-4940-4fa0-bbe7-17e784168987
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot5:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=3a2faa24-f516-4798-9fa7-260f60b9a2c8
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot6:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=919df147-87d3-4a71-bbb6-c556ee99ec61
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
  
  bot7:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=89d31b81-010c-496b-ae7e-5a39fd331686
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  bot8:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    environment:
      - BOT_SECRET=b3c2ce3a-d445-4ad7-bb12-27c327f21b3a
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  api:
    build:
      context: ./bot/
      dockerfile: Dockerfile-web
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
  
  dashboard:
    build: ./dashboard/
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
