name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the bot Docker image
      run: docker build ./bot/ --file bot/Dockerfile --tag hackathonbot:$(date +%s)
    
    - name: Build the api Image
      run: docker build ./bot/ --file bot/Dockerfile-web --tag api:$(date +%s)
    
    - name: Build the dashboard Image
      run: docker build ./dashboard/ --file dashboard/Dockerfile --tag dashboard:$(date +%s)